final_configs = [
    {"name": 'linear_all', "features": all_set, "model_kind": 'linear', "epochs": 20, "lr": 0.001, "weight_decay": 0.1},
    {"name": 'linear_tech', "features": technical_set, "model_kind": 'linear', "epochs": 20, "lr": 0.001, "weight_decay": 0.4},
    {"name": 'linear_volvol', "features": vol_volume_set, "model_kind": 'linear', "epochs": 20, "lr": 0.001, "weight_decay": 0.1},
    {"name": 'lstm_all', "features": all_set, "model_kind": 'lstm', "hidden": 32, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'lstm_hlrange_volspike', "features": ["high_low_range_20", "volume_spike_20"], "model_kind": 'lstm', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'lstm_mixed', "features": mixed_set, "model_kind": 'lstm', "hidden": 24, "epochs": 16, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'lstm_solo_gap', "features": ["gap"], "model_kind": 'lstm', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'lstm_solo_hlrange20', "features": ["high_low_range_20"], "model_kind": 'lstm', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'lstm_solo_industry_rev5', "features": ["industry_rev_5"], "model_kind": 'lstm', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'lstm_solo_mom5', "features": ["mom_5"], "model_kind": 'lstm', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'lstm_solo_rangepos', "features": ["range_pos"], "model_kind": 'lstm', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'lstm_solo_rangepos5', "features": ["range_pos_5"], "model_kind": 'lstm', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'lstm_solo_vol20', "features": ["vol_20"], "model_kind": 'lstm', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'lstm_solo_vol20industry', "features": ["vol_20_industry"], "model_kind": 'lstm', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'lstm_solo_volspike', "features": ["volume_spike_20"], "model_kind": 'lstm', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'lstm_solo_volspikeindustry', "features": ["volume_spike_20_industry"], "model_kind": 'lstm', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'lstm_volspike_rangepos', "features": ["volume_spike_20", "range_pos"], "model_kind": 'lstm', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'mlp_all', "features": all_set, "model_kind": 'mlp', "hidden": 48, "epochs": 22, "lr": 0.001, "weight_decay": 0.05},
    {"name": 'mlp_mixed', "features": mixed_set, "model_kind": 'mlp', "hidden": 32, "epochs": 20, "lr": 0.001, "weight_decay": 0.05},
    {"name": 'mlp_mom', "features": momentum_set, "model_kind": 'mlp', "hidden": 32, "epochs": 20, "lr": 0.001, "weight_decay": 0.05},
    {"name": 'mlp_rev', "features": reversal_set, "model_kind": 'mlp', "hidden": 32, "epochs": 20, "lr": 0.001, "weight_decay": 0.05},
    {"name": 'mlp_solo_hlrange20', "features": ["high_low_range_20"], "model_kind": 'mlp', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'mlp_solo_industry_rev5', "features": ["industry_rev_5"], "model_kind": 'mlp', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'mlp_solo_mom20', "features": ["mom_20"], "model_kind": 'mlp', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'mlp_solo_mom5', "features": ["mom_5"], "model_kind": 'mlp', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'mlp_solo_price_ma20', "features": ["price_to_ma20"], "model_kind": 'mlp', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'mlp_solo_vol20', "features": ["vol_20"], "model_kind": 'mlp', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'mlp_solo_vol20industry', "features": ["vol_20_industry"], "model_kind": 'mlp', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'mlp_solo_volspike', "features": ["volume_spike_20"], "model_kind": 'mlp', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'mlp_tech', "features": technical_set, "model_kind": 'mlp', "hidden": 32, "epochs": 20, "lr": 0.001, "weight_decay": 0.05},
    {"name": 'mlp_vol20_rangepos', "features": ["vol_20", "range_pos"], "model_kind": 'mlp', "hidden": 16, "epochs": 18, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'mlp_volvol', "features": vol_volume_set, "model_kind": 'mlp', "hidden": 32, "epochs": 20, "lr": 0.001, "weight_decay": 0.05},
    {"name": 'spline_all', "features": all_set, "model_kind": 'spline', "epochs": 20, "lr": 0.001, "weight_decay": 0.1},
    {"name": 'spline_mixed', "features": mixed_set, "model_kind": 'spline', "epochs": 20, "lr": 0.001, "weight_decay": 0.1},
    {"name": 'spline_rev', "features": reversal_set, "model_kind": 'spline', "epochs": 20, "lr": 0.001, "weight_decay": 0.1},
    {"name": 'spline_solo_hlrange20', "features": ["high_low_range_20"], "model_kind": 'spline', "epochs": 20, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'spline_solo_industry_rev5', "features": ["industry_rev_5"], "model_kind": 'spline', "epochs": 20, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'spline_solo_rangepos5', "features": ["range_pos_5"], "model_kind": 'spline', "epochs": 20, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'spline_solo_vol20', "features": ["vol_20"], "model_kind": 'spline', "epochs": 20, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'spline_solo_vol20industry', "features": ["vol_20_industry"], "model_kind": 'spline', "epochs": 20, "lr": 0.001, "weight_decay": 0.0},
    {"name": 'spline_tech', "features": technical_set, "model_kind": 'spline', "epochs": 20, "lr": 0.001, "weight_decay": 0.1},
]
